=== cedrosdev/winnetoujs/schemas/win.config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "serverPort": {
      "type": "number",
      "description": "Port for WinnetouJs Server VSCode Extension, default 3197."
    },
    "constructosPath": {
      "type": "string",
      "description": "The path of constructos."
    },
    "constructosOut": {
      "type": "string",
      "description": "The path of constructos release."
    },
    "apps": {
      "type": "array",
      "description": "Array of apps to be compiled in Webpack (Available since 1.19.0).",
      "items": {
        "type": "object",
        "properties": {
          "entry": {
            "type": "string",
            "description": "Entry file for the application."
          },
          "out": {
            "type": "string",
            "description": "Output file for the application."
          }
        },
        "required": ["entry", "out"]
      }
    },
    "entry": {
      "type": ["string", "object"],
      "description": "Deprecated since 1.19.0, use apps instead."
    },
    "out": {
      "type": ["string", "object"],
      "description": "Deprecated since 1.19.0, use apps instead."
    },
    "sass": {
      "type": "array",
      "description": "The path of sass files to be compiled and watched.",
      "items": {
        "type": "object",
        "properties": {
          "entryFolder": {
            "type": "string",
            "description": "Entry folder for SASS."
          },
          "outFolder": {
            "type": "string",
            "description": "Release folder for SASS."
          },
          "firstFile": {
            "type": "string",
            "description": "The file that needs to be at the top of the CSS bundle."
          }
        },
        "required": ["entryFolder", "outFolder"]
      }
    },
    "defaultLang": {
      "type": "string",
      "description": "Initial language, default is 'en-us'."
    },
    "publicPath": {
      "type": "string",
      "description": "Relative path address to the translations folder."
    },
    "icons": {
      "type": "string",
      "description": "The path of icons."
    }
  },
  "required": ["constructosPath", "constructosOut", "apps"],
  "description": "Schema for the IWinConfig configuration object."
}

=== cedrosdev/winnetoujs/scaffolding/win.config.json
{
  "$schema": "./node_modules/winnetoujs/schemas/win.config.schema.json",
  "defaultLang": "en-us",
  "publicPath": "/",
  "constructosPath": "./constructos",
  "constructosOut": "./js/constructos",
  "apps": [
    {
      "entry": "./js/app.js",
      "out": "./release"
    }
  ],
  "sass": [
    {
      "entryFolder": "./sass",
      "outFolder": "./release"
    }
  ]
}
